In [17]:
import pandas as pd

# Read in the CSV file
df = pd.read_csv("Total_2023-03-25.csv")

# Group the data by every 8 rows
grouped_data = df.groupby(df.index // 8)
new_df = grouped_data.agg({"item": list, "value": list})
new_df

                                             item                                              value
0     [总市值, 流通市值, 行业, 上市时间, 股票代码, 股票简称, 总股本, 流通股]  [9842435069.58, 6852288136.740001, 农药兽药, 20100...
1     [总市值, 流通市值, 行业, 上市时间, 股票代码, 股票简称, 总股本, 流通股]  [4913062727.27, 4913062727.27, 电子元件, 20070720,...
2     [总市值, 流通市值, 行业, 上市时间, 股票代码, 股票简称, 总股本, 流通股]  [4182154136.7, 3399803774.6499996, 农牧饲渔, 20091...
3     [总市值, 流通市值, 行业, 上市时间, 股票代码, 股票简称, 总股本, 流通股]  [11987950718.199999, 11987950718.199999, 农药兽药,...
4     [总市值, 流通市值, 行业, 上市时间, 股票代码, 股票简称, 总股本, 流通股]  [3338535720.0000005, 3338535720.0000005, 农药兽药,...
...                                           ...                                                ...
5092  [总市值, 流通市值, 行业, 上市时间, 股票代码, 股票简称, 总股本, 流通股]  [1797600000.0, 620621400.0, 化学制品, 20201023, 68...
5093  [总市值, 流通市值, 行业, 上市时间, 股票代码, 股票简称, 总股本, 流通股]  [2246469800.0, 2246469800.0, 化学制品, 20140909, 6...
5094  [总市值, 流通市值, 行业, 上市时间, 股票代码, 股票简称, 总股本, 流通股]  [33346651565.0, 33346651565.0, 化学制品, 20030801,...
5095  [总市值, 流通市值, 行业, 上市时间, 股票代码, 股票简称, 总股本, 流通股]  [11451649279.5, 9352919728.95, 化学制品, 20120801,...
5096  [总市值, 流通市值, 行业, 上市时间, 股票代码, 股票简称, 总股本, 流通股]  [7735271140.16, 6366777220.48, 塑料制品, 20141010,...

[5097 rows x 2 columns]

In [16]:


data = dict(zip(new_df["item"][0], new_df["value"][0]))
data

{'总市值': '9842435069.58',
 '流通市值': '6852288136.740001',
 '行业': '农药兽药',
 '上市时间': '20100917',
 '股票代码': '300119',
 '股票简称': '瑞普生物',
 '总股本': '468018786.0',
 '流通股': '325833958.0'}

In [23]:
df = pd.DataFrame(columns=new_df["item"][0])
data = dict(zip(new_df["item"][0], new_df["value"][0]))
for index,row in new_df.iterrows():
#     print(row["item"])
    data = dict(zip(row["item"], row["value"]))
    df = pd.concat([df, pd.DataFrame([data])], ignore_index=True)
#     final_df.append(data, ignore_index=True)
# df = pd.concat([df, pd.DataFrame([data])], ignore_index=True)
# # final_df.append(data, ignore_index=True)
# data1 = dict(zip(new_df["item"][1], new_df["value"][1]))
# df = pd.concat([df, pd.DataFrame([data1])], ignore_index=True)


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5097 entries, 0 to 5096
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   总市值     5097 non-null   object
 1   流通市值    5097 non-null   object
 2   行业      5097 non-null   object
 3   上市时间    5097 non-null   object
 4   股票代码    5097 non-null   object
 5   股票简称    5097 non-null   object
 6   总股本     5097 non-null   object
 7   流通股     5097 non-null   object
dtypes: object(8)
memory usage: 318.7+ KB

In [24]:
df.head()

                  总市值                流通市值  ...           总股本           流通股
0       9842435069.58   6852288136.740001  ...   468018786.0   325833958.0
1       4913062727.27       4913062727.27  ...  1134656519.0  1134656519.0
2        4182154136.7  3399803774.6499996  ...   862299822.0   700990469.0
3  11987950718.199999  11987950718.199999  ...  1120369226.0  1120369226.0
4  3338535720.0000005  3338535720.0000005  ...   410644000.0   410644000.0

[5 rows x 8 columns]

In [ ]:
df.to_csv("总股本_em.csv",index=False)

In [ ]:


# Aggregate the values in each group into a single row


# Rename the columns of the new dataframe
new_df.columns = ["item_grouped", "value_grouped"]

new_df

In [ ]:
import pandas as pd

# Read in the CSV file
df = pd.read_csv("Totalbak_2023-03-25.csv")

# Group the data by every 8 rows
grouped_data = df.groupby(df.index // 8)

# Aggregate the values in each group into a single row
new_df = grouped_data.agg({"item": list, "value": list})

# Concatenate the lists in the "item_grouped" and "value_grouped" columns into a single row
new_df["item_grouped"] = new_df["item_grouped"].apply(
    lambda x: [elem for sublist in x for elem in sublist])
new_df["value_grouped"] = new_df["value_grouped"].apply(
    lambda x: [elem for sublist in x for elem in sublist])

# Create a new dataframe with the concatenated columns
final_df = pd.DataFrame(
    {"item": new_df["item_grouped"], "value": new_df["value_grouped"]})
final_df